-- Member number: the order in which people joined. The first person to sign
-- up is 1. The badge shows it next to the tier ("Attendee · 0002").

alter table public.profiles add column member_no integer;

-- Existing badges get their number in sign-up order.
update public.profiles p
set member_no = n.no
from (select id, row_number() over (order by created_at, id) as no from public.profiles) n
where p.id = n.id;

-- New badges take the next number.
alter table public.profiles
  alter column member_no set not null,
  alter column member_no add generated by default as identity,
  add constraint profiles_member_no_key unique (member_no);

select setval(
  pg_get_serial_sequence('public.profiles', 'member_no'),
  coalesce((select max(member_no) from public.profiles), 0) + 1,
  false
);

-- The number never changes from the client. Admins (postgres, service role)
-- can still fix it by hand.
create function public.lock_member_no() returns trigger
language plpgsql as $$
begin
  if new.member_no is distinct from old.member_no
    and current_user in ('anon', 'authenticated')
  then
    raise exception 'member number cannot be changed' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger profiles_lock_member_no
  before update of member_no on public.profiles
  for each row execute function public.lock_member_no();
